[project]
name = "e-mahhir"
version = "0.1.0"
description = "e-mahhir backend system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "sqlalchemy[asyncio]>=2.0",
    "asyncpg>=0.29.0",
    "python-dotenv>=1.0.1",
    "loguru"
]
